# Generated by Django 4.1.7 on 2023-03-27 05:33

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adventure',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('adv_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('adv_name', models.CharField(max_length=100)),
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('start_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
                ('duration', models.IntegerField()),
                ('capacity', models.IntegerField(default=10)),
                ('schedule_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.IntegerField(default=0)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('package_activities', models.ManyToManyField(blank=True, related_name='activities', to='myapp1.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='packagebookingData',
            fields=[
                ('package_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('People', models.IntegerField()),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('Comments', models.CharField(max_length=100)),
                ('TotalPrice', models.CharField(default=0, max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.client')),
            ],
        ),
        migrations.CreateModel(
            name='bookingData',
            fields=[
                ('booking_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('People', models.IntegerField()),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('13 PM', '13 PM'), ('14 PM', '14 PM'), ('15 PM', '15 AM'), ('16 PM', '16 PM'), ('17 PM', '17 PM'), ('18 PM', '18 PM'), ('19 PM', '19 PM'), ('20 PM', '20 PM'), ('21 PM', '21 PM')], default='9 AM', max_length=10)),
                ('Comments', models.CharField(max_length=100)),
                ('TotalPrice', models.CharField(default=0, max_length=100)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.client')),
            ],
        ),
    ]
