# Generated by Django 4.1.7 on 2023-04-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_bookingdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
