# Generated by Django 4.1.7 on 2023-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_adventure_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
